name: Update Youtube Videos

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  update-youtube-videos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Update README with youtube videos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE-VIDEOS-LIST"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCQB_obfDOF6unm-q4U2R5jA"
          max_post_count: 5